name: Docker Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login Docker
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    
    - name: Build and Push the Docker image
      run: |
        docker build . --file Dockerfile --tag bernnardosbo/nginx-frontend:${{ github.run_number }}
        docker push bernnardosbo/nginx-frontend:${{ github.run_number }}
        
  updateYaml:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: changing manifests of k8s
      with:
        repository: 'BernnardoSBO/tp2-cloud-manifests'
        token: ${{ secrets.GIT_PASSWORD }}
        
    - name: Change k8s manifest so ArgoCD can push new images
      run: |
        git config user.email GIT@ACTIONS.COM
        git config user.name new_yaml_modification
        pwd
        cat config.yaml
        pwd
        sed -i "s+bernnardosbo/nginx-frontend.*+bernnardosbo/nginx-frontend:ga-$RUN_NUMBER+g" config.yaml
        cat config.yaml
        git add .
        git commit -m 'GithubActions: changed manifest (id: $RUN_NUMBER)'
        git push origin master
      env:
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
        RUN_NUMBER: ${{ github.run_number }}
    
